import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { TrackRequestModalComponent } from '../../components/track-request-modal/track-request-modal.component';
import { CrossRoleService, FlowSIV } from '../../../../core/services/cross-role.service';
import { CurrentUserService } from '../../../../core/services/current-user.service';

interface SIV {
  id: string;
  sivNumber: string;
  requestId: string;
  requestTitle: string;
  issueDate: string;
  status: string;
}

@Component({
  selector: 'app-my-sivs',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
  templateUrl: './my-sivs.component.html',
  styleUrls: ['./my-sivs.component.scss'],
})
export class MySIVsComponent implements OnInit {
  private readonly modalService = inject(NgbModal);
  private readonly crossRoleService = inject(CrossRoleService);
  private readonly currentUserService = inject(CurrentUserService);

  protected readonly isLoading = signal(false);
  protected readonly error = signal<string | null>(null);
  protected readonly sivs = signal<SIV[]>([]);

  ngOnInit(): void {
    this.loadSIVs();
  }

  private loadSIVs(): void {
    const user = this.currentUserService.getCurrentUserValue();
    const employeeId = user?.id ?? '';
    const identity = user
      ? { username: user.username, fullName: user.fullName, email: user.email }
      : undefined;

    this.isLoading.set(true);
    this.error.set(null);

    this.crossRoleService.getSIVsForEmployee(employeeId, identity).subscribe({
      next: (flowSIVs: FlowSIV[]) => {
        const mapped: SIV[] = flowSIVs.map((s) => ({
          id: s.id,
          sivNumber: s.sivNumber,
          requestId: s.srNumber,
          requestTitle: s.srNumber,
          issueDate: s.issueDate,
          status: s.status,
        }));
        this.sivs.set(mapped);
        this.isLoading.set(false);
      },
      error: (err: unknown) => {
        this.error.set('Failed to load SIVs. Please try again.');
        this.isLoading.set(false);
        console.error('[MySIVsComponent] Error loading SIVs:', err);
      },
    });
  }

  viewDetails(requestId: string): void {
    const modalRef = this.modalService.open(TrackRequestModalComponent, {
      fullscreen: true,
      backdrop: 'static',
      windowClass: 'track-request-fullscreen-modal',
    });
    modalRef.componentInstance.srNumber = requestId;
    modalRef.componentInstance.status = 'Completed';
  }

  async downloadPDF(siv: SIV): Promise<void> {
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.setTextColor(30, 41, 59);
    doc.text('AFRICOM Asset Management Platform', 20, 25);

    doc.setFontSize(16);
    doc.setTextColor(71, 85, 105);
    doc.text('Store Issue Voucher (SIV)', 20, 35);

    doc.setLineWidth(0.5);
    doc.setDrawColor(203, 213, 225);
    doc.line(20, 42, 190, 42);

    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);

    let startY = 55;
    const lineHeight = 10;

    doc.setFont('helvetica', 'bold');
    doc.text('SIV Number:', 20, startY);
    doc.setFont('helvetica', 'normal');
    doc.text(siv.sivNumber, 60, startY);
    startY += lineHeight;

    doc.setFont('helvetica', 'bold');
    doc.text('Request ID:', 20, startY);
    doc.setFont('helvetica', 'normal');
    doc.text(siv.requestId, 60, startY);
    startY += lineHeight;

    doc.setFont('helvetica', 'bold');
    doc.text('Request Title:', 20, startY);
    doc.setFont('helvetica', 'normal');
    doc.text(siv.requestTitle, 60, startY);
    startY += lineHeight;

    doc.setFont('helvetica', 'bold');
    doc.text('Issue Date:', 20, startY);
    doc.setFont('helvetica', 'normal');
    doc.text(siv.issueDate, 60, startY);
    startY += lineHeight;

    doc.setFont('helvetica', 'bold');
    doc.text('Status:', 20, startY);
    doc.setTextColor(16, 185, 129);
    doc.text(siv.status, 60, startY);

    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184);
    doc.setFont('helvetica', 'italic');
    doc.text('This document was automatically generated by the PAS system.', 20, 280);

    doc.save(`${siv.sivNumber}_Document.pdf`);
  }
}
