import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { TrackRequestModalComponent } from '../../components/track-request-modal/track-request-modal.component';

interface SIV {
  id: string;
  sivNumber: string;
  requestId: string;
  requestTitle: string;
  issueDate: string;
  status: string;
}

@Component({
  selector: 'app-my-sivs',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './my-sivs.component.html',
  styleUrls: ['./my-sivs.component.scss'],
})
export class MySIVsComponent {
  private readonly modalService = inject(NgbModal);

  protected readonly sivs = signal<SIV[]>([
    {
      id: '1',
      sivNumber: 'SIV-2024-001',
      requestId: 'REQ-005',
      requestTitle: 'Desk Setup',
      issueDate: '2024-01-22',
      status: 'Issued',
    },
    {
      id: '2',
      sivNumber: 'SIV-2024-002',
      requestId: 'REQ-006',
      requestTitle: 'Headset Request',
      issueDate: '2024-01-21',
      status: 'Issued',
    },
  ]);

  viewDetails(requestId: string): void {
    const modalRef = this.modalService.open(TrackRequestModalComponent, {
      fullscreen: true,
      backdrop: 'static',
      windowClass: 'track-request-fullscreen-modal'
    });
    modalRef.componentInstance.srNumber = requestId;
    modalRef.componentInstance.status = 'Completed'; // SIV implies it was completed
  }

  async downloadPDF(siv: SIV): Promise<void> {
    // Dynamically import jsPDF to prevent SSR errors and improve load times
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF();

    // Add styling and content to the PDF
    doc.setFontSize(20);
    doc.setTextColor(30, 41, 59); // Slate-800
    doc.text('AFRICOM Asset Management Platform', 20, 25);

    doc.setFontSize(16);
    doc.setTextColor(71, 85, 105); // Slate-500
    doc.text('Store Issue Voucher (SIV)', 20, 35);

    // Line
    doc.setLineWidth(0.5);
    doc.setDrawColor(203, 213, 225); // Slate-300
    doc.line(20, 42, 190, 42);

    // Details
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59); // Slate-800
    
    let startY = 55;
    const lineHeight = 10;
    
    doc.setFont('helvetica', 'bold');
    doc.text('SIV Number:', 20, startY);
    doc.setFont('helvetica', 'normal');
    doc.text(siv.sivNumber, 60, startY);
    startY += lineHeight;

    doc.setFont('helvetica', 'bold');
    doc.text('Request ID:', 20, startY);
    doc.setFont('helvetica', 'normal');
    doc.text(siv.requestId, 60, startY);
    startY += lineHeight;

    doc.setFont('helvetica', 'bold');
    doc.text('Request Title:', 20, startY);
    doc.setFont('helvetica', 'normal');
    doc.text(siv.requestTitle, 60, startY);
    startY += lineHeight;

    doc.setFont('helvetica', 'bold');
    doc.text('Issue Date:', 20, startY);
    doc.setFont('helvetica', 'normal');
    doc.text(siv.issueDate, 60, startY);
    startY += lineHeight;

    doc.setFont('helvetica', 'bold');
    doc.text('Status:', 20, startY);
    doc.setTextColor(16, 185, 129); // Emerald-500
    doc.text(siv.status, 60, startY);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(148, 163, 184); // Slate-400
    doc.setFont('helvetica', 'italic');
    doc.text('This document was automatically generated by the PAS system.', 20, 280);

    // Trigger download
    doc.save(`${siv.sivNumber}_Document.pdf`);
  }
}
