import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

interface ApprovalReport {
  id: string;
  reportName: string;
  generatedBy: string;
  generatedDate: string;
  totalApprovals: number;
  totalRejections: number;
  avgResponseTime: string;
  details?: {
    approvedRequests: Array<{ requestNumber: string; requester: string; amount: number; date: string }>;
    rejectedRequests: Array<{ requestNumber: string; requester: string; amount: number; date: string; reason: string }>;
  };
}

@Component({
  selector: 'app-approval-reports',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './approval-reports.component.html',
  styleUrls: ['./approval-reports.component.scss']
})
export class ApprovalReportsComponent {
  protected readonly reports = signal<ApprovalReport[]>([
    {
      id: '1',
      reportName: 'Monthly Approval Report - Jan 2024',
      generatedBy: 'System',
      generatedDate: '2024-01-31',
      totalApprovals: 45,
      totalRejections: 5,
      avgResponseTime: '2.3 hours',
      details: {
        approvedRequests: [
          { requestNumber: 'SR-2024-001', requester: 'John Doe', amount: 5000, date: '2024-01-15' },
          { requestNumber: 'SR-2024-003', requester: 'Jane Smith', amount: 3200, date: '2024-01-18' }
        ],
        rejectedRequests: [
          { requestNumber: 'SR-2024-002', requester: 'Bob Wilson', amount: 8000, date: '2024-01-16', reason: 'Budget exceeded' }
        ]
      }
    }
  ]);

  protected selectedReport = signal<ApprovalReport | null>(null);
  protected showDetailsModal = signal(false);

  viewReport(report: ApprovalReport): void {
    this.selectedReport.set(report);
    this.showDetailsModal.set(true);
  }

  closeDetailsModal(): void {
    this.showDetailsModal.set(false);
    this.selectedReport.set(null);
  }

  downloadReport(report: ApprovalReport): void {
    console.log('Downloading report:', report.reportName);
    
    const content = `
      APPROVAL REPORT
      ===============
      
      Report Name: ${report.reportName}
      Generated By: ${report.generatedBy}
      Generated Date: ${report.generatedDate}
      
      SUMMARY:
      --------
      Total Approvals: ${report.totalApprovals}
      Total Rejections: ${report.totalRejections}
      Average Response Time: ${report.avgResponseTime}
      
      APPROVED REQUESTS:
      ------------------
      ${report.details?.approvedRequests.map(req => 
        `${req.requestNumber} - ${req.requester} - $${req.amount} - ${req.date}`
      ).join('\n      ') || 'No approved requests'}
      
      REJECTED REQUESTS:
      ------------------
      ${report.details?.rejectedRequests.map(req => 
        `${req.requestNumber} - ${req.requester} - $${req.amount} - ${req.date} - Reason: ${req.reason}`
      ).join('\n      ') || 'No rejected requests'}
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.reportName.replace(/\s+/g, '_')}.txt`;
    link.click();
    window.URL.revokeObjectURL(url);
    
    alert(`Downloaded ${report.reportName} as text file. In production, this would be a PDF.`);
  }
}
