import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  downloadReportPdf,
  ReportDetailRow,
} from '../compliance-reports/report-actions.util';
import { ManagerDataService } from '../../../../core/services/manager-data.service';

interface ApprovalReport {
  id: string;
  reportName: string;
  generatedBy: string;
  generatedDate: string;
  totalApprovals: number;
  totalRejections: number;
  avgResponseTime: string;
  details?: {
    approvedRequests: Array<{ requestNumber: string; requester: string; amount: number; date: string }>;
    rejectedRequests: Array<{ requestNumber: string; requester: string; amount: number; date: string; reason: string }>;
  };
}

@Component({
  selector: 'app-approval-reports',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './approval-reports.component.html',
  styleUrls: ['./approval-reports.component.scss']
})
export class ApprovalReportsComponent implements OnInit {
  private readonly managerData = inject(ManagerDataService);

  protected readonly reports = signal<ApprovalReport[]>([]);

  protected selectedReport = signal<ApprovalReport | null>(null);
  protected showDetailsModal = signal(false);

  ngOnInit(): void {
    this.managerData.syncServiceRequests().subscribe(() => {
      const approved = this.managerData.requestRows('approved');
      const rejected = this.managerData.requestRows('rejected');
      this.reports.set([
        {
          id: 'approval-current',
          reportName: `Approval Decision Report - ${new Date().toLocaleDateString()}`,
          generatedBy: 'Backend data',
          generatedDate: new Date().toLocaleDateString(),
          totalApprovals: approved.length,
          totalRejections: rejected.length,
          avgResponseTime: 'Calculated by backend data',
          details: {
            approvedRequests: approved.map((row) => ({
              requestNumber: row.requestNumber,
              requester: row.requesterName,
              amount: row.estimatedValue,
              date: row.approvedDate || row.requestedDate,
            })),
            rejectedRequests: rejected.map((row) => ({
              requestNumber: row.requestNumber,
              requester: row.requesterName,
              amount: row.estimatedValue,
              date: row.rejectedDate || row.requestedDate,
              reason: row.rejectionReason || 'No reason provided',
            })),
          },
        },
      ]);
    });
  }

  viewReport(report: ApprovalReport): void {
    this.selectedReport.set(report);
    this.showDetailsModal.set(true);
  }

  closeDetailsModal(): void {
    this.showDetailsModal.set(false);
    this.selectedReport.set(null);
  }

  async downloadReport(report: ApprovalReport): Promise<void> {
    await downloadReportPdf('Approval Report', report.reportName, this.buildDetails(report));
  }

  protected totalDecisions(report: ApprovalReport): number {
    return report.totalApprovals + report.totalRejections;
  }

  protected approvalRate(report: ApprovalReport): number {
    const total = this.totalDecisions(report);
    return total > 0 ? Math.round((report.totalApprovals / total) * 100) : 0;
  }

  protected totalApprovedValue(report: ApprovalReport): number {
    return report.details?.approvedRequests.reduce((sum, req) => sum + req.amount, 0) ?? 0;
  }

  protected totalRejectedValue(report: ApprovalReport): number {
    return report.details?.rejectedRequests.reduce((sum, req) => sum + req.amount, 0) ?? 0;
  }

  private buildDetails(report: ApprovalReport): ReportDetailRow[] {
    return [
      { label: 'Report Name', value: report.reportName },
      { label: 'Generated By', value: report.generatedBy },
      { label: 'Generated Date', value: report.generatedDate },
      { label: 'Total Decisions', value: this.totalDecisions(report) },
      { label: 'Total Approvals', value: report.totalApprovals },
      { label: 'Total Rejections', value: report.totalRejections },
      { label: 'Approval Rate', value: `${this.approvalRate(report)}%` },
      { label: 'Average Response Time', value: report.avgResponseTime },
      { label: 'Approved Value', value: `$${this.totalApprovedValue(report).toLocaleString()}` },
      { label: 'Rejected Value', value: `$${this.totalRejectedValue(report).toLocaleString()}` },
      {
        label: 'Approved Requests',
        value:
          report.details?.approvedRequests
            .map((req) => `${req.requestNumber} | ${req.requester} | $${req.amount.toLocaleString()} | ${req.date}`)
            .join('\n') || 'No approved requests',
      },
      {
        label: 'Rejected Requests',
        value:
          report.details?.rejectedRequests
            .map(
              (req) =>
                `${req.requestNumber} | ${req.requester} | $${req.amount.toLocaleString()} | ${req.date} | ${req.reason}`,
            )
            .join('\n') || 'No rejected requests',
      },
    ];
  }
}
