import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  downloadReportPdf,
  ReportDetailRow,
} from '../compliance-reports/report-actions.util';
import { ManagerDataService } from '../../../../core/services/manager-data.service';

interface RequestReport {
  id: string;
  reportName: string;
  generatedBy: string;
  generatedDate: string;
  totalRequests: number;
  pendingRequests: number;
  approvedRequests: number;
  totalValue: number;
  details?: {
    requests: Array<{ 
      requestNumber: string; 
      requester: string; 
      department: string;
      status: string;
      amount: number; 
      date: string;
    }>;
  };
}

@Component({
  selector: 'app-request-reports',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './request-reports.component.html',
  styleUrls: ['./request-reports.component.scss']
})
export class RequestReportsComponent implements OnInit {
  private readonly managerData = inject(ManagerDataService);

  protected readonly reports = signal<RequestReport[]>([]);

  protected selectedReport = signal<RequestReport | null>(null);
  protected showDetailsModal = signal(false);

  ngOnInit(): void {
    this.managerData.syncServiceRequests().subscribe(() => {
      const requests = this.managerData.requestRows();
      this.reports.set([
        {
          id: 'requests-current',
          reportName: `Department Request Report - ${new Date().toLocaleDateString()}`,
          generatedBy: 'Backend data',
          generatedDate: new Date().toLocaleDateString(),
          totalRequests: requests.length,
          pendingRequests: requests.filter((row) => row.status === 'Pending').length,
          approvedRequests: requests.filter((row) => row.status === 'Approved').length,
          totalValue: requests.reduce((sum, row) => sum + row.estimatedValue, 0),
          details: {
            requests: requests.map((row) => ({
              requestNumber: row.requestNumber,
              requester: row.requesterName,
              department: row.department,
              status: row.status,
              amount: row.estimatedValue,
              date: row.requestedDate,
            })),
          },
        },
      ]);
    });
  }

  viewReport(report: RequestReport): void {
    this.selectedReport.set(report);
    this.showDetailsModal.set(true);
  }

  closeDetailsModal(): void {
    this.showDetailsModal.set(false);
    this.selectedReport.set(null);
  }

  async downloadReport(report: RequestReport): Promise<void> {
    await downloadReportPdf('Department Request Report', report.reportName, this.buildDetails(report));
  }

  protected completedRequests(report: RequestReport): number {
    return Math.max(0, report.totalRequests - report.pendingRequests - report.approvedRequests);
  }

  protected approvalRate(report: RequestReport): number {
    return report.totalRequests > 0 ? Math.round((report.approvedRequests / report.totalRequests) * 100) : 0;
  }

  protected averageRequestValue(report: RequestReport): number {
    return report.totalRequests > 0 ? Math.round(report.totalValue / report.totalRequests) : 0;
  }

  protected departmentsCovered(report: RequestReport): string {
    const departments = new Set(report.details?.requests.map((request) => request.department).filter(Boolean));
    return Array.from(departments).join(', ') || 'No departments';
  }

  private buildDetails(report: RequestReport): ReportDetailRow[] {
    return [
      { label: 'Report Name', value: report.reportName },
      { label: 'Generated By', value: report.generatedBy },
      { label: 'Generated Date', value: report.generatedDate },
      { label: 'Departments Covered', value: this.departmentsCovered(report) },
      { label: 'Total Requests', value: report.totalRequests },
      { label: 'Pending Requests', value: report.pendingRequests },
      { label: 'Approved Requests', value: report.approvedRequests },
      { label: 'Other/Completed Requests', value: this.completedRequests(report) },
      { label: 'Approval Rate', value: `${this.approvalRate(report)}%` },
      { label: 'Total Value', value: `$${report.totalValue.toLocaleString()}` },
      { label: 'Average Request Value', value: `$${this.averageRequestValue(report).toLocaleString()}` },
      {
        label: 'Request Details',
        value:
          report.details?.requests
            .map(
              (req) =>
                `${req.requestNumber} | ${req.requester} | ${req.department} | ${req.status} | $${req.amount.toLocaleString()} | ${req.date}`,
            )
            .join('\n') || 'No requests',
      },
    ];
  }
}
