import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

interface RequestReport {
  id: string;
  reportName: string;
  generatedBy: string;
  generatedDate: string;
  totalRequests: number;
  pendingRequests: number;
  approvedRequests: number;
  totalValue: number;
  details?: {
    requests: Array<{ 
      requestNumber: string; 
      requester: string; 
      department: string;
      status: string;
      amount: number; 
      date: string;
    }>;
  };
}

@Component({
  selector: 'app-request-reports',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './request-reports.component.html',
  styleUrls: ['./request-reports.component.scss']
})
export class RequestReportsComponent {
  protected readonly reports = signal<RequestReport[]>([
    {
      id: '1',
      reportName: 'Monthly Request Report - Jan 2024',
      generatedBy: 'System',
      generatedDate: '2024-01-31',
      totalRequests: 50,
      pendingRequests: 5,
      approvedRequests: 40,
      totalValue: 125000,
      details: {
        requests: [
          { requestNumber: 'SR-2024-001', requester: 'John Doe', department: 'IT', status: 'Approved', amount: 5000, date: '2024-01-15' },
          { requestNumber: 'SR-2024-002', requester: 'Jane Smith', department: 'HR', status: 'Pending', amount: 3200, date: '2024-01-18' },
          { requestNumber: 'SR-2024-003', requester: 'Bob Wilson', department: 'Finance', status: 'Approved', amount: 8000, date: '2024-01-20' }
        ]
      }
    }
  ]);

  protected selectedReport = signal<RequestReport | null>(null);
  protected showDetailsModal = signal(false);

  viewReport(report: RequestReport): void {
    this.selectedReport.set(report);
    this.showDetailsModal.set(true);
  }

  closeDetailsModal(): void {
    this.showDetailsModal.set(false);
    this.selectedReport.set(null);
  }

  downloadReport(report: RequestReport): void {
    console.log('Downloading report:', report.reportName);
    
    const content = `
      DEPARTMENT REQUEST REPORT
      =========================
      
      Report Name: ${report.reportName}
      Generated By: ${report.generatedBy}
      Generated Date: ${report.generatedDate}
      
      SUMMARY:
      --------
      Total Requests: ${report.totalRequests}
      Pending Requests: ${report.pendingRequests}
      Approved Requests: ${report.approvedRequests}
      Total Value: $${report.totalValue.toLocaleString()}
      
      REQUESTS DETAIL:
      ----------------
      ${report.details?.requests.map(req => 
        `${req.requestNumber} - ${req.requester} (${req.department}) - ${req.status} - $${req.amount} - ${req.date}`
      ).join('\n      ') || 'No requests'}
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.reportName.replace(/\s+/g, '_')}.txt`;
    link.click();
    window.URL.revokeObjectURL(url);
    
    alert(`Downloaded ${report.reportName} as text file. In production, this would be a PDF.`);
  }
}
