import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  downloadReportPdf,
  ReportDetailRow,
} from '../compliance-reports/report-actions.util';
import { ManagerDataService } from '../../../../core/services/manager-data.service';

interface SIVReport {
  id: string;
  reportName: string;
  generatedBy: string;
  generatedDate: string;
  totalSIVs: number;
  totalItemsIssued: number;
  totalValue: number;
  details?: {
    sivs: Array<{ 
      sivNumber: string; 
      requester: string; 
      department: string;
      itemsCount: number;
      value: number; 
      date: string;
    }>;
  };
}

@Component({
  selector: 'app-siv-reports',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './siv-reports.component.html',
  styleUrls: ['./siv-reports.component.scss']
})
export class SIVReportsComponent implements OnInit {
  private readonly managerData = inject(ManagerDataService);

  protected readonly reports = signal<SIVReport[]>([]);

  protected selectedReport = signal<SIVReport | null>(null);
  protected showDetailsModal = signal(false);

  ngOnInit(): void {
    this.managerData.getSivs().subscribe((sivs) => {
      this.reports.set([
        {
          id: 'sivs-current',
          reportName: `SIV Report - ${new Date().toLocaleDateString()}`,
          generatedBy: 'Backend data',
          generatedDate: new Date().toLocaleDateString(),
          totalSIVs: sivs.length,
          totalItemsIssued: sivs.reduce((sum, siv) => sum + siv.totalItems, 0),
          totalValue: sivs.reduce((sum, siv) => sum + siv.totalValue, 0),
          details: {
            sivs: sivs.map((siv) => ({
              sivNumber: siv.sivNumber,
              requester: siv.requesterName,
              department: siv.department,
              itemsCount: siv.totalItems,
              value: siv.totalValue,
              date: siv.issueDate,
            })),
          },
        },
      ]);
    });
  }

  viewReport(report: SIVReport): void {
    this.selectedReport.set(report);
    this.showDetailsModal.set(true);
  }

  closeDetailsModal(): void {
    this.showDetailsModal.set(false);
    this.selectedReport.set(null);
  }

  async downloadReport(report: SIVReport): Promise<void> {
    await downloadReportPdf('Store Issue Voucher Report', report.reportName, this.buildDetails(report));
  }

  protected averageSivValue(report: SIVReport): number {
    return report.totalSIVs > 0 ? Math.round(report.totalValue / report.totalSIVs) : 0;
  }

  protected averageItemsPerSiv(report: SIVReport): number {
    return report.totalSIVs > 0 ? Math.round((report.totalItemsIssued / report.totalSIVs) * 10) / 10 : 0;
  }

  protected departmentsCovered(report: SIVReport): string {
    const departments = new Set(report.details?.sivs.map((siv) => siv.department).filter(Boolean));
    return Array.from(departments).join(', ') || 'No departments';
  }

  private buildDetails(report: SIVReport): ReportDetailRow[] {
    return [
      { label: 'Report Name', value: report.reportName },
      { label: 'Generated By', value: report.generatedBy },
      { label: 'Generated Date', value: report.generatedDate },
      { label: 'Departments Covered', value: this.departmentsCovered(report) },
      { label: 'Total SIVs', value: report.totalSIVs },
      { label: 'Total Items Issued', value: report.totalItemsIssued },
      { label: 'Average Items Per SIV', value: this.averageItemsPerSiv(report) },
      { label: 'Total Value', value: `$${report.totalValue.toLocaleString()}` },
      { label: 'Average SIV Value', value: `$${this.averageSivValue(report).toLocaleString()}` },
      {
        label: 'SIV Details',
        value:
          report.details?.sivs
            .map(
              (siv) =>
                `${siv.sivNumber} | ${siv.requester} | ${siv.department} | ${siv.itemsCount} item(s) | $${siv.value.toLocaleString()} | ${siv.date}`,
            )
            .join('\n') || 'No SIVs',
      },
    ];
  }
}
