import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

interface SIVReport {
  id: string;
  reportName: string;
  generatedBy: string;
  generatedDate: string;
  totalSIVs: number;
  totalItemsIssued: number;
  totalValue: number;
  details?: {
    sivs: Array<{ 
      sivNumber: string; 
      requester: string; 
      department: string;
      itemsCount: number;
      value: number; 
      date: string;
    }>;
  };
}

@Component({
  selector: 'app-siv-reports',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './siv-reports.component.html',
  styleUrls: ['./siv-reports.component.scss']
})
export class SIVReportsComponent {
  protected readonly reports = signal<SIVReport[]>([
    {
      id: '1',
      reportName: 'Monthly SIV Report - Jan 2024',
      generatedBy: 'System',
      generatedDate: '2024-01-31',
      totalSIVs: 35,
      totalItemsIssued: 120,
      totalValue: 87500,
      details: {
        sivs: [
          { sivNumber: 'SIV-2024-001', requester: 'John Doe', department: 'IT', itemsCount: 3, value: 5348, date: '2024-01-20' },
          { sivNumber: 'SIV-2024-002', requester: 'Jane Smith', department: 'Operations', itemsCount: 1, value: 2800, date: '2024-01-21' },
          { sivNumber: 'SIV-2024-003', requester: 'Bob Wilson', department: 'Finance', itemsCount: 5, value: 4200, date: '2024-01-22' }
        ]
      }
    }
  ]);

  protected selectedReport = signal<SIVReport | null>(null);
  protected showDetailsModal = signal(false);

  viewReport(report: SIVReport): void {
    this.selectedReport.set(report);
    this.showDetailsModal.set(true);
  }

  closeDetailsModal(): void {
    this.showDetailsModal.set(false);
    this.selectedReport.set(null);
  }

  downloadReport(report: SIVReport): void {
    console.log('Downloading report:', report.reportName);
    
    const content = `
      STORE ISSUE VOUCHER REPORT
      ==========================
      
      Report Name: ${report.reportName}
      Generated By: ${report.generatedBy}
      Generated Date: ${report.generatedDate}
      
      SUMMARY:
      --------
      Total SIVs: ${report.totalSIVs}
      Total Items Issued: ${report.totalItemsIssued}
      Total Value: $${report.totalValue.toLocaleString()}
      
      SIV DETAILS:
      ------------
      ${report.details?.sivs.map(siv => 
        `${siv.sivNumber} - ${siv.requester} (${siv.department}) - ${siv.itemsCount} items - $${siv.value} - ${siv.date}`
      ).join('\n      ') || 'No SIVs'}
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.reportName.replace(/\s+/g, '_')}.txt`;
    link.click();
    window.URL.revokeObjectURL(url);
    
    alert(`Downloaded ${report.reportName} as text file. In production, this would be a PDF.`);
  }
}
